models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct
    parameters:
      temperature: 0.3

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the Redis Vector Search Bot.
      The bot is designed to answer questions about vector search with Redis.
      The bot is knowledgeable about Redis vector search capabilities.
      If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hi there. Can you help me with some questions I have about Redis vector search?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about Redis vector search capabilities and configuration. What would you like to know?"
  user "What vector index methods does Redis support?"
    ask question about Redis vector capabilities
  bot respond to question about Redis vector capabilities
    "Redis supports two vector indexing methods:  Flat (Brute-force index) and HNSW (approximate nearest neighbor)"

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output